require('./common_epub.js').buildEpub({
  srcMd: '低电_排版版.md',
  epubOut: '低电.epub',
  bookId: 'urn:uuid:43f930d3-698f-43df-82b2-1c775a114199',
  bookTitle: '低电',
  bookTitleEn: 'LOW POWER',
  bookSubtitle: '路易斯安那系列·上篇',
  bookSeriesEn: 'CALL OF CTHULHU · SOUTHERN LOUISIANA SERIES · PART I',
  creator: '歌味觉死',
  editor: 'r0k1s#i',
  description: '克苏鲁跑团 Replay《低电》路易斯安那系列·上篇，OCR 校对整理版。',
  bilibiliUrl: 'https://www.bilibili.com/video/BV1V24y177sX',
  coverImage: 'tools/images/cover_low_power.png',
  authorAvatar: 'tools/images/author_avatar.jpg',
  disclaimer: '视频由2021年的网团大面积魔改而成自娱自乐，切勿当真。视频可能包含各类令人不适的描述，请积极回避。',
  appendices: ['低电_制作人员_排版版.md'],
});
